services:
  mysql:
    image: mysql:8.4
    container_name: riffrank-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    command: ["mysqld", "--mysql-native-password=ON"]
    volumes:
      - riffrank_mysql_data:/var/lib/mysql
      - ./docker/mysql/init:/docker-entrypoint-initdb.d

volumes:
  riffrank_mysql_data:

