server:
  port: 8084
  error:
    include-message: always
    include-binding-errors: always
    include-exception: true

spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/riffrank_user
    username: ${MYSQL_USER:riffrank}
    password: ${MYSQL_PASSWORD:riffrank}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        jdbc:
          batch_size: 20
          fetch_size: 50
        order_inserts: true
        order_updates: true
        type:
          preferred_uuid_jdbc_type: CHAR
    hibernate:
      ddl-auto: update
    open-in-view: false
  flyway:
    enabled: false

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: health,info

jwt:
  secret: "riffrank-super-secret-key-for-jwt-hs512-algorithm-minimum-64-chars-required-for-security-compliance"
  expiration-ms: 2592000000

logging:
  level:
    root: INFO
